services:
    php-dev:
        volumes:
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
            - ./_host-volumes/app:/app:delegated
        depends_on:
            - db
        environment:
            - PHP_ENABLE_XDEBUG=1
        ports:
            - "8103:80"

    db:
        image: mariadb:10.6.15
        restart: always
        command: --character-set-server=utf8 --collation-server=utf8_general_ci
        environment:
            MYSQL_DATABASE: "db"
            # So you don't have to use root, but you can if you like
            MYSQL_USER: "db"
            # You can use whatever password you like
            MYSQL_PASSWORD: "db"
            # Password for root access
            MYSQL_ROOT_PASSWORD: "Meni1971"
        volumes:
            - data:/var/lib/mysql

    pma:
        image: phpmyadmin
        depends_on:
            - db
        environment:
            - PMA_ARBITRARY=1
        restart: always
        ports:
            - 8003:80

    composer_installation:
        image: composer
        volumes:
            - ./_host-volumes/app:/app:delegated
        command: composer update --ignore-platform-reqs

volumes:
    data:
